### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by FrancoisGallard** [scilab/svn-prerequirements#1]
This repo seems empty. Where are the files that used to be in svn://svn.scilab.org/scilab/trunk/Dev-Tools/SE/Prerequirements ?

**Comment by davidcl** [comment]
we migrated to gitlab not github, the SVN has been discarded in favor of archives available on https://oos.eu-west-2.outscale.com/scilab-releases-dev/prerequirements/prerequirements-scilab-branch-main-windows_x64.zip for windows x64.
